# Generated by Django 4.2.10 on 2024-03-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Sub-Category",
                "verbose_name_plural": "Sub-Categories",
            },
        ),
    ]
